import Head from "next/head";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Products from "../components/Products";
import ContactUs from "../components/ContactUs";
import Footer from "../components/Footer";

export default function Style() {
  return (
    <div>
      <Head>
        <title>VACA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/VACA-logo.svg" />
      </Head>
      <Navbar />
      <Header />
      <Products />
      <ContactUs />
      <Footer />
    </div>
  );
}
